# File: .github/workflows/validate-bicep.yml

on:
  workflow_dispatch:
  pull_request:
      branches:
      - 'main'
      - 'releases/**'

name: Validate Bicep code

jobs:
  build-and-validate-bicep:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: PSRule analysis
        uses: microsoft/ps-rule@v2.7.0
        with:
          modules: PSRule.Rules.Azure
          inputType: repository
          outputFormat: Sarif
          outcome: Processed

      - name: Build Bicep
        run: bicep build src/bicep/main.bicep

      - name: Run What-If bicep deployment
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          region: 'westeurope'
          template: src/bicep/main.bicep
          parameters: src/bicep/main.parameters.json emToken=${{ secrets.EMTOKEN }}
          additionalArguments: "--what-if"
